14 спринт
AtamasMaria/java-shareit pull request #4
Opened 2023-04-20 14:43 UTC by AtamasMaria

2023-04-20 21:30 UTC, AtamasMaria commented
Не могу понять почему тут заваливаются тесты((( в postman проходят все

2023-04-21 13:44 UTC, AtamasMaria commented
Я правда тут нахимичила с коммитами, я пыталась их сплющить, но попытка провалилась(

2023-04-21 14:33 UTC, ohelly requested changes
Привет! В целом отличная работа, прекрасный код. Есть одно небольшое замечание, которое необходимо поправить. Также я оставил ряд рекомендаций, на которые стоит обратить внимание.

2023-04-21 14:33 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    private final BookingRepository bookingRepository;
Рекомендация: Будет лучше, если к букингам обращаться через их сервис, как сделано с userService.

2023-04-21 14:33 UTC, ohelly commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        if (itemService.findOwnerId(booking.getItem().getId()).equals(userId)
Рекомендация: переменную ownerId можно вынести, чтобы не делать два раза один и тот же запрос.
![image](https://user-images.githubusercontent.com/51891976/233659814-69a1bbf8-5fde-4f74-bc7e-0af411984af9.png)

2023-04-21 14:33 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        System.out.println(bookings);
Рекомендация: System.out лучше не использовать, вывод через логгер - лучший выбор

2023-04-21 14:33 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public List<ItemDto> findAllUsersItems(Long userId) {
Необходимо исправить: Необходимо также сетить отзывы в итемы, аналогично тому, как сделано в методе получения итема по идентификатору.

2023-04-21 14:33 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        List<Comment> comments = commentRepository.findAllByItemId(result.getId());
Рекомендация: Комменты можно добавить в entity итемов(сейчас есть только итемы в комментах) и тогда не придется делать запрос вручную, они подтянутся автоматически.

2023-04-21 17:03 UTC, AtamasMaria commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    private final BookingRepository bookingRepository;
Не могу это поправить по причине того что программа не запускается если в ItemService есть ссылка на BookingService, а в BookingService есть ссылка на ItemService) Поэтому оставляю так как есть )

2023-04-21 20:43 UTC, AtamasMaria commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        List<Comment> comments = commentRepository.findAllByItemId(result.getId());
Попыталась сделать как в рекомендации и получить через стандартный метод findAllById(), но что-то не срастается, поэтому метод свой оставила

2023-04-21 20:43 UTC, AtamasMaria commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public List<ItemDto> findAllUsersItems(Long userId) {
Исправила)

2023-04-22 16:51 UTC, ohelly approved these changes
Привет! Отлично, исправлены все замечания! Работу принимаю, можно двигаться дальше. Удачи в дальнейшем обучении!

2023-04-22 17:26 UTC, merged