15 спринт (без тестов)
AtamasMaria/java-shareit pull request #5
Opened 2023-04-30 23:42 UTC by AtamasMaria

2023-05-04 22:29 UTC, AtamasMaria commented
Добавила тесты, но опять та же проблема что меня всегда преследует, тесты на постмане проходят, а здесь валятся(

2023-05-05 17:58 UTC, AtamasMaria commented
Подправила схему и все прошло)

2023-05-05 20:36 UTC, ohelly requested changes
Привет! Отличная работа, у меня нет замечаний, все супер! Есть только одна очень важная рекомендация, на которую стоит потратить хотя бы немного времени. Также рекомендую создать интерфейсы для классов сервисов.
Если возникнут вопросы с транзакциями можно написать в пачку.
Также можно просто прислать этот же вариант работы на проверку и я его приму.

2023-05-05 20:36 UTC, ohelly commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> +    public ItemRequestDto create(ItemRequestDto itemRequestDto, Long userId) {
Рекомендация: Над методами, которые делают запросы в БД всегда лучше вешать аннотацию ``@Transactional``. Транзакции очень важная вещь, про которые будут спрашивать на собесах 100%. Рекомендую с ними ознакомиться.

2023-05-06 14:56 UTC, AtamasMaria commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> +    public ItemRequestDto create(ItemRequestDto itemRequestDto, Long userId) {
добавила интерфейсы и в реквесты добавила аннотацию

2023-05-06 18:18 UTC, ohelly approved these changes
Привет! Все супер, работу принимаю. Удачи в дальнейшем обучении!

2023-05-07 12:34 UTC, merged